"""
Django settings for ask_permyakova project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g&e_6h^qn8_03p(1kj43$!+mb3+7slf#8-$qn87ua0#bpd5r4#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1', 'http://askme.localhost']


# Application definition

INSTALLED_APPS = [
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ask_permyakova.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ask_permyakova.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'ask_permyakova_db'),      
        'USER': os.environ.get('POSTGRES_USER', 'uuser'),           
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'ppassword'),       
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),               
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),                
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}
print("POSTGRES_HOST:", os.environ.get('POSTGRES_HOST'))
print("POSTGRES_DB:", os.environ.get('POSTGRES_DB'))
print("POSTGRES_USER:", os.environ.get('POSTGRES_USER'))

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
 
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # BASE_DIR / "static",
    # "/var/www/static/",
]
 


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

centrifugo_host = os.environ.get('CENTRIFUGO_HOST', '127.0.0.1') 
centrifugo_port = os.environ.get('CENTRIFUGO_PORT', '9000') 
CENTRIFUGO_DOMAIN = f'{centrifugo_host}:{centrifugo_port}'
CENTRIFUGO_SECRET_KEY = "my_secret"
CENTRIFUGO_API_KEY = "my_api_key"
print(f"CENTRIFUGO_DOMAIN: {CENTRIFUGO_DOMAIN}")

redis_username = os.environ.get('REDIS_USER', 'kredis') 
redis_password = os.environ.get('REDIS_PASSWORD', '1111') 
redis_host = os.environ.get('REDIS_HOST', 'localhost') 
redis_port = os.environ.get('REDIS_PORT', '6379') 
redis_url = f"redis://{redis_username}:{redis_password}@{redis_host}:{redis_port}/0"
CELERY_BROKER_URL = redis_url
CELERY_RESULT_BACKEND = redis_url
print(f"CELERY_BROKER_URL: {CELERY_BROKER_URL}")